tornado:
  type: Article
  title: Tornado Cash Privacy Solution v1.4
  author: [A. Pertsev, R. Semenov, R. Storm]
  date: 2019-12-17
  url: https://berkeley-defi.github.io/assets/material/Tornado%20Cash%20Whitepaper.pdf

schnorr:
  type: Article
  title: Efficient Signature Generation by Smart Cards
  author: C. P. Schnorr
  organization: Universität Frankfurt
  date: 1991
  url: https://link.springer.com/content/pdf/10.1007/BF00196725.pdf
  parent:
    type: Journal
    title: Journal of Cryptology
    issue: 4
    page-range: 161-174
    publisher: International Association for Cryptologic Research

fiat-shamir:
  type: Article
  author: [A. Fiat, A. Shamir]
  organization: The Weizmann Institute of Science
  date: 1986
  title: "How To Prove Yourself: Practical Solutions to Identification and Signature Problems"
  url: https://link.springer.com/content/pdf/10.1007/3-540-47721-7_12.pdf
  parent:
    type: Conference
    title: Advances in Cryptology -- CRYPTO '86
    page-range: 186-194

mimc:
  type: Article
  author: [M. Albrecht, L. Grassi, C. Rechberger, A. Roy, T. Tiessen]
  title: "MiMC: Efficient Encryption and Cryptographic Hashing with Minimal Multiplicative Complexity"
  date: 2016
  url: https://eprint.iacr.org/2016/492.pdf
  publisher: Cryptology ePrint Archive

snark:
  type: Article
  title: Succinct Non-Interactive Zero Knowledge for a von Neumann Architecture
  author: [E. Ben-Sasson, A. Chiesa, E. Tromer, M. Virza]
  date: 2019
  url: https://eprint.iacr.org/2013/879.pdf
  publisher: Cryptology ePrint Archive

stark:
  type: Article
  url: https://eprint.iacr.org/2018/046.pdf
  publisher: Cryptology ePrint Archive
  date: 2018
  author: [E. Ben-Sasson, I. Bentov, Y. Horesh, М. Riabzev]
  title: Scalable, transparent, and post-quantum secure computational integrity

bulletproof:
  type: Article
  url: https://eprint.iacr.org/2017/1066.pdf
  publisher: Cryptology ePrint Archive
  date: 2017
  author: [В. Bünz, J. Bootle, D. Boneh, A. Poelstra, P. Wuille, G. Maxwell]
  title: "Bulletproofs: Short Proofs for Confidential Transactions and More"

plonk:
  type: article
  url: https://eprint.iacr.org/2019/953.pdf
  publisher: Cryptology ePrint Archive
  date: 2022
  organization: Aztec
  author: [A. Gabizon, Z. J. Williamson, O. Ciobotaru]
  title: "PlonK: Permutations over Lagrange-bases for Oecumenical Noninteractive arguments of Knowledge"

zcash:
  type: Article
  url: https://zips.z.cash/protocol/protocol.pdf
  date: 2022
  author: [D. Hopwood, S. Bowe, T. Hornby, N. Wilcox]
  title: Zcash Protocol Specification

monero:
  type: Article
  url: https://eprint.iacr.org/2018/535.pdf
  publisher: Cryptology ePrint Archive
  date: 2018
  author: [K. M. Alonso, J. H. Joancomarti]
  title: "Monero: Privacy in the blockchain"

mimblewimble:
  type: Article
  url: https://eprint.iacr.org/2020/1064.pdf
  date: 2020
  author: G. Yu
  title: Mimblewimble Non-Interactive Transaction Scheme

merkle:
  url: https://eprint.iacr.org/2016/683.pdf
  type: Article
  date: 2016
  title: Efficient Sparse Merkle Trees
  author: [R. Dahlberg, T. Pulls, R. Peeters]
  publisher: Cryptology ePrint Archive

aave:
  type: Article
  url: https://github.com/aave/protocol-v2/blob/master/aave-v2-whitepaper.pdf
  title: AAVE protocol whitepaper v2.0
  date: 2020
  author: [E. Boado, S. Kulechov]

aztec:
  type: Article
  url: https://github.com/AztecProtocol/aztec-v1/blob/master/AZTEC.pdf
  title: The AZTEC Protocol
  author: Z. J. Williamson
  date: 2018

this:
  url: https://github.com/ly0va/thesis
  title: Реалізація протоколу анонімних переказів на основі доказів з нульовим розголошенням
  author: Л. Потьомкін
  date: 2023
